### ISSUE TITLE
加入pgweb部署

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#10]
加入pgweb部署
* 只有read权限
* pgweb被supervisor启动

**Comment by kainwen** [comment]
* 创建一个postgres的普通账户
* 只给他grant oj的数据库
* 只给grantoj数据的只读权限
* pgweb开启的时候，要加参数，pgweb好像就有readonly模式。然后只开一个session。
* 开机自启动，最好加入在supervisor下

**Comment by kainwen** [comment]
* `create role xxx with login CONNECTION LIMIT 1 PASSWORD abcd  ENCRYPTED `
* `grant CONNECT  on database lambdaoj`
* `grant select on table xxx`

最后一步的xxx我来定义一些view就好了。

**Comment by prajnamort** [comment]
Done.
