### ISSUE TITLE
类似去年的口号，可以想办法加进来，或者想新的。

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#11]
去年是用lisp写的。今年看看用啥办法。

**Comment by prajnamort** [comment]
嗯？？你是说去年那个主页？

**Comment by kainwen** [comment]
@prajnamort 对。可以有用新的方式加入进来，这个优先级不高。

**Comment by prajnamort** [comment]
嗯，但这个其实我觉得没有啥地方能加耶。。你试试设计一下，那个页面你觉得能加？ @kainwen

**Comment by kainwen** [comment]
先close了再说吧。考虑想加个新需求，把oj作为我们的一个有用的窗口传播一些东西。
