### ISSUE TITLE
import lib需要考虑兼容性问题

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#15]
https://github.com/prajnamort/LambdaOJ2/blob/master/main/utils/compare_utils.py#L7

这里我记得3.4和3.6行为是不同的。

**Comment by prajnamort** [comment]
我看过这个，但根据我的尝试我那个用法应该是没问题的。
你可以上传一个判题函数试试。

**Comment by kainwen** [comment]
@prajnamort 不是判断函数的问题，而是py环境的问题。代码是开源的，假如别人要用，部署时候用了3.6版本的py，就会挂了吧。

**Comment by prajnamort** [comment]
![image](https://user-images.githubusercontent.com/5914441/30277253-d4ebd3fc-9739-11e7-9585-29c1f806a677.png)
我就是在 3.5 和 3.6 的 python 里面都试过了呀，这个没问题。
python 官方文档里也没说那个函数会过时。
