### ISSUE TITLE
内存溢出等错误时，时间和内存应该显示为 "-"

### ISSUE THREAD

**Issue by WeitaoVan** [prajnamort/LambdaOJ2#2]
![0](https://user-images.githubusercontent.com/16603489/30256739-6ed79c86-96df-11e7-895d-33f3e0c8a7f5.png)

如图

**Comment by kainwen** [comment]
@WeitaoVan 原因是C++需要的运行时内存比较大，改成2M就可能过了。 @prajnamort  可以关闭这个issue了

**Comment by prajnamort** [comment]
哦？你试过改 2M 能通过了？

**Comment by prajnamort** [comment]
@kainwen  不过，其实那个显示有点问题，就是超过了的时候，是不能获取实际当前运行时间和内存的嘛？

**Comment by prajnamort** [comment]
如果有某些状态不能的话，我觉得应该显示 "-" 而不是 "0ms" 和 "0KB"

**Comment by kainwen** [comment]
@prajnamort 对测试过了。
这个feature是别的oj都这样。我也就没管了。新feature不那么重要，回头再说把。

**Comment by prajnamort** [comment]
好的，feature 先留在 issue 里面，先不要关掉，不然就不知道了

**Comment by WeitaoVan** [comment]
![75](https://user-images.githubusercontent.com/16603489/30261629-2ade9982-9700-11e7-9406-d83d7ff9c4ab.png)

为什么只能得75分

**Comment by kainwen** [comment]
@WeitaoVan  因为4的测试数据巨大无比，int无法容纳。溢出了。要拿100分，得自己用字符串模拟大整数。

**Comment by prajnamort** [comment]
@WeitaoVan 对，这是个彩蛋，故意的。
