### ISSUE TITLE
BUG: the same user login at the same time in different machine

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#23]
When ZinanLin login my account on his computer, I got wrong page.

![screen shot 2017-09-12 at 12 39 18 pm](https://user-images.githubusercontent.com/2275669/30308366-6fe00c7a-97b7-11e7-97fb-10b046937737.png)

"退出" has no response and nothing in the page.

**Comment by kainwen** [comment]
It seems the same as https://github.com/prajnamort/LambdaOJ2/issues/22.
If confirmed, close this.

**Comment by prajnamort** [comment]
Duplicate as #22.
