### ISSUE TITLE
security issue: we should make compile process running in docker

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#25]

**Comment by kainwen** [comment]
目前我设计了一个思路：
* 弄一个docker image，里面安装部署上需要跑的环境
* 每次celery的task被处罚的时候，起一个container，挂载一个数据盘上去（含有题目必要的磁盘上得文件
* 运行一个命令python去判题
* 想法把判题的结果从docker里发给celery的task
* 关闭刚刚起的container

**Comment by prajnamort** [comment]
#31 Done.
