### ISSUE TITLE
定时任务：自动将一天后判题没有成功的任务设置为「判题失败」状态

### ISSUE THREAD

**Issue by prajnamort** [prajnamort/LambdaOJ2#27]

**Comment by kainwen** [comment]
@prajnamort 我感觉celery超过最大次数的时候，可以直接做这个事情。看看celery有没有接口，要么可以在celery线程了捕捉到当前是第几次重拾，要么可能有hook函数再最后一次fail了做些事情。

**Comment by prajnamort** [comment]
Done.
