### ISSUE TITLE
在管理“提交”的页面加入搜索功能

### ISSUE THREAD

**Issue by WeitaoVan** [prajnamort/LambdaOJ2#3]
![default](https://user-images.githubusercontent.com/16603489/30256813-f9e29830-96df-11e7-91b2-e27fc47c6ee2.png)

如图，建议加入新功能：根据‘ID’或’用户名’搜索提交记录。

**Comment by prajnamort** [comment]
该功能已经添加:  `提交 ID` 是精确匹配， `用户名` 是前缀匹配。
