### ISSUE TITLE
 backup

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#33]
我们应该做backup，但是不应该用整盘的backup。
应该只需要备份postgres的数据和内容，以及一些关键的磁盘里的数据和内容。

周期性存在一个硬盘里。然后再周期性的upload到云上（比如阿里云或者腾讯云的类似s3服务上）。

**Comment by kainwen** [comment]
@prajnamort 感觉可以用这个 https://cloud.tencent.com/product/cas#wiki

**Comment by prajnamort** [comment]
整盘备份有什么问题嘛？

**Comment by kainwen** [comment]
@prajnamort 主要我没听说过业界有谁是这么做的。

**Comment by prajnamort** [comment]
可以问问，我觉得这样挺省心的，也不会因为漏掉什么出问题，反正盘够大。

**Comment by kainwen** [comment]
@prajnamort 我记得整盘备份有bug？

**Comment by kainwen** [comment]
@prajnamort 可以查查看如何做snapshot啥的

**Comment by prajnamort** [comment]
那是之前用 dump 方式有问题，因为 dump 保存的东西只能用 restore 还原。
现在是 rsync 方式，就是普通文件，直接可读。所以问题应该木有了。

**Comment by prajnamort** [comment]
之前 dump 就类似磁盘 snapshot ，感觉反而可能有问题哟。。

**Comment by prajnamort** [comment]
因为最后 restore 失败了，不知道为啥。。然后 snapshot 文件又不可直接读，所以= =

**Comment by kainwen** [comment]
弄好了就关闭这个issue

**Comment by prajnamort** [comment]
Done.
