### ISSUE TITLE
Rejudge 功能

### ISSUE THREAD

**Issue by JY-Zhou** [prajnamort/LambdaOJ2#38]
可不可以添加一个Rejudge功能？
就是对一道题目的全部提交或指定的提交重新评测，主要是为了有测试数据更新的情况使用。

**Comment by prajnamort** [comment]
暂不添加该功能，这个主要是题目的正确率统计需要改动，然后之后的通知比较麻烦。
如果真的有重新测评功能，就需要一个地方显示当前重新测评的 submit list 里面，每一个 submit 在测评前后 score 的变化，这样助教才能及时通知那些分数因此下降了的学生尽快重新提交。

如果有时间做的话可以提个 PR，需要的话可以把开发用的 vagrant 镜像上传给你。
