### ISSUE TITLE
sumit detail time display bug

### ISSUE THREAD

**Issue by kainwen** [prajnamort/LambdaOJ2#41]
liblambdaoj already runs time in ms, as documented here:
![screen shot 2017-09-27 at 8 29 11 am](https://user-images.githubusercontent.com/2275669/30890213-21561abe-a2f1-11e7-97a2-bdd6459ff378.png)

And in this submit : http://lambda.ee.tsinghua.edu.cn/#/submit/1626 
It seems frontend has multiplied 1000 on the data in DB.

**Comment by prajnamort** [comment]
Done.
