### ISSUE TITLE
搞个排行榜；点集查询这题卡一下离线算法

### ISSUE THREAD

**Issue by mazeyu** [prajnamort/LambdaOJ2#45]
一般的oj都有排行榜吧？？

然后点集查询这题加一下一些数据：下一个点的坐标根据上个点的答案（取模之类）得到，这样来卡一下树状数组等离线算法

**Comment by kainwen** [comment]
@mazeyu 排行榜是status么？以前有，这版故意没有的。因为这不是普通oj，就是给大家提交作业的。之前有些人不愿意被别人看到自己的提交情况。

我们不是助教，不管和题目本身相关的一切问题。只负责oj本身。

**Comment by mazeyu** [comment]
不完全是status，status可以没有，可以每道题下面弄一个通过的榜，当然用户也可以不愿意被显示（我只是随便提提，不行也没事）
和题目相关的那就算了

**Comment by Sweetyshadow** [comment]
我觉得可以在个人中心里添加一个用户是否愿意自己的提交情况被纳入排行的复选框吧

**Comment by prajnamort** [comment]
如 @kainwen 所言，这次是故意不做这个页面的，本学期结束后考虑反馈情况再做商议。
